# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = ChattingServer
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"../../../../../../../../Qt/5.14.1/msvc2017_64/lib"
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(ChattingServer.pri)
